from abc import ABC, abstractmethod
from typing import List, Dict, Any, AsyncIterator

class AIProvider(ABC):
    """Abstract base class for all AI model providers."""

    @abstractmethod
    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        config: Dict[str, Any]
    ) -> str:
        """Generates a complete text response asynchronously."""
        pass

    @abstractmethod
    async def generate_stream(
        self,
        messages: List[Dict[str, str]],
        config: Dict[str, Any]
    ) -> AsyncIterator[str]:
        """Streams text chunks as they are generated by the model."""
        pass

    @abstractmethod
    async def test_connection(self, config: Dict[str, Any]) -> Dict[str, Any]:
        """Tests the connection to the provider and model."""
        pass
